// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-2OCgdQZSNbAfQ0KXIjTxwDnaLgckwyA',
    appId: '1:252727300670:web:11dc5106b9c991da49376f',
    messagingSenderId: '252727300670',
    projectId: 'marketplace-uas-hio',
    authDomain: 'marketplace-uas-hio.firebaseapp.com',
    storageBucket: 'marketplace-uas-hio.firebasestorage.app',
    measurementId: 'G-R91D9V7703',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn3T2TawVuuO-2rA5HxKenYmy-mQZ40pY',
    appId: '1:252727300670:android:7929efce327a675549376f',
    messagingSenderId: '252727300670',
    projectId: 'marketplace-uas-hio',
    storageBucket: 'marketplace-uas-hio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSobtYyHsLlMfKuEFijnC7jwfJ_TLCz4',
    appId: '1:252727300670:ios:bb39016d8ca4265c49376f',
    messagingSenderId: '252727300670',
    projectId: 'marketplace-uas-hio',
    storageBucket: 'marketplace-uas-hio.firebasestorage.app',
    iosBundleId: 'com.example.semangatMandiriWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSobtYyHsLlMfKuEFijnC7jwfJ_TLCz4',
    appId: '1:252727300670:ios:bb39016d8ca4265c49376f',
    messagingSenderId: '252727300670',
    projectId: 'marketplace-uas-hio',
    storageBucket: 'marketplace-uas-hio.firebasestorage.app',
    iosBundleId: 'com.example.semangatMandiriWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-2OCgdQZSNbAfQ0KXIjTxwDnaLgckwyA',
    appId: '1:252727300670:web:0c4b95e4c25c2ba649376f',
    messagingSenderId: '252727300670',
    projectId: 'marketplace-uas-hio',
    authDomain: 'marketplace-uas-hio.firebaseapp.com',
    storageBucket: 'marketplace-uas-hio.firebasestorage.app',
    measurementId: 'G-KP1KQ8HJVW',
  );
}
